### ISSUE TITLE
Canvas-prebuilt causes errors in webpack

### ISSUE THREAD

**Issue by nyurik** [node-gfx/node-canvas-prebuilt#23]
I'm building a [plugin for Kibana](https://github.com/nyurik/kibana-vega-vis) that uses [Vega](https://github.com/vega/vega) library.  Kibana dynamically compiles all of the client-side code using webpack on the server side, before sending it to the browser. Recently, Vega added canvas-prebuilt dependency, and I cannot upgrade to it because now webpack in the build process throws this error. 

Node 6.11.3, on Ubuntu 17.04

```
    ERROR in .-vega-vis/~/canvas-prebuilt/canvas/lib/bindings.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../build/Release/canvas in /home/yurik/dev/elastic/kibana-vega-vis/node_modules/canvas-prebuilt/canvas/lib
     @ .-vega-vis/~/canvas-prebuilt/canvas/lib/bindings.js 3:17-51

    at Object.exports.create (/home/yurik/dev/elastic/kibana/node_modules/boom/lib/index.js:21:17)
    at LazyOptimizer.failedStatsToError (/home/yurik/dev/elastic/kibana/src/optimize/base_optimizer.js:224:17)
    at Compiler.<anonymous> (/home/yurik/dev/elastic/kibana/src/optimize/lazy/lazy_optimizer.js:42:24)
    at Compiler.applyPlugins (/home/yurik/dev/elastic/kibana/node_modules/tapable/lib/Tapable.js:26:37)
    at Watching._done (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compiler.js:78:17)
    at Watching.<anonymous> (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compiler.js:51:17)
    at /home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/home/yurik/dev/elastic/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/home/yurik/dev/elastic/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/home/yurik/dev/elastic/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/home/yurik/dev/elastic/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/home/yurik/dev/elastic/kibana/node_modules/webpack/lib/Compilation.js:567:9)
```

**Comment by nyurik** [comment]
Cross-posted at https://github.com/vega/vega-scenegraph/issues/55

**Comment by chearon** [comment]
It'll definitely fail if webpack tries to load it - seems like a problem in vega/vega-scenegraph, and it looks like it was fixed there?

**Comment by zbjornson** [comment]
Not positive, but canvas-prebuilt's `package.json` should maybe specify `"browser": "browser.js"` [like node-canvas does](https://github.com/Automattic/node-canvas/blob/master/package.json#L6). That should stop webpack from trying to bundle native files. ([cryptic documentation](https://webpack.js.org/configuration/resolve/#resolve-mainfields))

**Comment by chearon** [comment]
Thanks @zbjornson, added to `package.json`
