### ISSUE TITLE
`npm i canvas@2.0.0-alpha.10` fail with 404

### ISSUE THREAD

**Issue by zixia** [node-gfx/node-canvas-prebuilt#34]
```shell
$ npm i canvas@2.0.0-alpha.10

> canvas@2.0.0-alpha.10 install /home/zixia/git/node-facenet/node_modules/canvas
> node-pre-gyp install

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.10/canvas-prebuilt-v2.0.0-alpha.10-node-v59-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/zixia/git/node-facenet/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:132:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/zixia/git/node-facenet/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:127:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:444:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:127:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:269:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:256:11)
node-pre-gyp ERR! System Linux 4.13.0-36-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/zixia/git/node-facenet/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/zixia/git/node-facenet/node_modules/canvas
node-pre-gyp ERR! node -v v9.7.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.0.0-alpha.10/canvas-prebuilt-v2.0.0-alpha.10-node-v59-linux-x64.tar.gz
```

Link to https://github.com/Automattic/node-canvas/issues/1111

**Comment by chearon** [comment]
I've created release binaries through alpha 12

**Comment by zixia** [comment]
Thanks!
