### ISSUE TITLE
Can't install 2.0.0 Alpha 12 on Ubuntu 17.10

### ISSUE THREAD

**Issue by JaviChaques** [node-gfx/node-canvas-prebuilt#35]
Hi,
I try to install last version, 2.0.0 Alpha 12 and can't install on Ubuntu 17.10:
This is the error, package doesn't exist 404:

> node-pre-gyp ERR! install error 
> node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.12/canvas-prebuilt-v2.0.0-alpha.12-node-v59-linux-x64.tar.gz
> node-pre-gyp ERR! stack     at Request.<anonymous> (/home/javichaques/Development/Typescript/Inbounder/functions/node_modules/node-pre-gyp/lib/install.js:118:27)
> node-pre-gyp ERR! stack     at Request.emit (events.js:185:15)
> node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/javichaques/Development/Typescript/Inbounder/functions/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
> node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:180:13)
> node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:539:21)
> node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
> node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:444:20)
> node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:180:13)
> node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:269:12)
> node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:256:11)
> node-pre-gyp ERR! System Linux 4.13.0-38-generic
> node-pre-gyp ERR! command "/usr/local/bin/node" "/home/javichaques/Development/Typescript/Inbounder/functions/node_modules/.bin/node-pre-gyp" "install"
> node-pre-gyp ERR! cwd /home/javichaques/Development/Typescript/Inbounder/functions/node_modules/canvas-prebuilt
> node-pre-gyp ERR! node -v v9.9.0
> node-pre-gyp ERR! node-pre-gyp -v v0.6.39
> node-pre-gyp ERR! not ok 
> 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.12/canvas-prebuilt-v2.0.0-alpha.12-node-v59-linux-x64.tar.gz
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! canvas-prebuilt@2.0.0-alpha.12 install: `node-pre-gyp install`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the canvas-prebuilt@2.0.0-alpha.12 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/javichaques/.npm/_logs/2018-04-11T15_23_30_270Z-debug.log

Thank you

**Comment by chearon** [comment]
It's a bug in node-pre-gyp. See https://github.com/Automattic/node-canvas/issues/1110#issuecomment-379457474. There's PR which fixes it that hasn't been released yet.

You can force the old `node-pre-gyp` like this:

```
npm install node-pre-gyp@0.6.39
npm install canvas-prebuilt@2.0.0-alpha.12
```

**Comment by JaviChaques** [comment]
Not working to me, the poblem is the build isn't exist:
> 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.12/canvas-prebuilt-v2.0.0-alpha.12-node-v59-linux-x64.tar.gz

**Comment by JaviChaques** [comment]
@chearon In release, the version 2.0.0 alpha.12-node-v59 is only available for Mac OS and Windows, I need for linux.

I want use custom fonts on my canvas.

Thank you!

**Comment by chearon** [comment]
Yeah sorry, you're right. Looks like the build didn't complete successfully. It will take some time to diagnose it since it builds on an old system in order to support older `glibc`.  In the meantime, the older alphas should have working node 9 builds.
