### ISSUE TITLE
Support node 10

### ISSUE THREAD

**Issue by molant** [node-gfx/node-canvas-prebuilt#36]
Hello all,

node 10.0.0 has been released and it would be great to have a version compatible with it. Hopefully this time there are [less issues with npm](https://github.com/node-gfx/node-canvas-prebuilt/issues/26).

Thanks a lot!

**Comment by molant** [comment]
@chearon I've seen you've done a commit to add node 10 a few days ago and some of the releases already have the v64 but not all. Are all the releases going to get support or just the ones that have it now?

Thanks!

**Comment by chearon** [comment]
I'm doing it for all of them but I start with the latest (alpha) version and go down the list to 1.6.x. It just takes a while to run all the builds, but I'm almost done with the alphas.

**Comment by chearon** [comment]
All done!

**Comment by molant** [comment]
🎉 thanks a lot!

**Comment by chearon** [comment]
Could you post the error?

**Comment by goldfire** [comment]
@chearon 

```
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/path/to/node_modules/node-pre-gyp/lib/install.js:118:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/path/to/node_modules/node-pre-gyp/node_modules/request/request.js:1074:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:432:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:283:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:264:11)
node-pre-gyp ERR! System Darwin 17.6.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/path/to/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /path/to/node_modules/identicon/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v10.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.0/canvas-prebuilt-v1.6.0-node-v64-darwin-x64.tar.gz
```

**Comment by chearon** [comment]
1.6.0 doesn't work on node 10. You need `v1.6.5-prerelease.1`

**Comment by slim16165** [comment]
> 1.6.0 doesn't work on node 10. You need `v1.6.5-prerelease.1`

Sorry, I'm new to NPM

I have tried 
npm install --save-dev canvas-prebuild

And I get:
```
npm ERR! code E404
npm ERR! 404 Not Found: canvas-prebuild@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utente\AppData\Roaming\npm-cache\_logs\2019-01-24T17_50_06_189Z-debug.log
```

If I try: npm install --save-dev canvas
```
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.3.1/canvas-v2.3.1-node-v64-win32-unknown-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.3.1 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Utente\Anaconda3\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Utente\\Dropbox\\Siti internet\\Altri siti\\ilcomuneinforma.it\\UnCSS\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=C:\\Users\\Utente\\Dropbox\\Siti internet\\Altri siti\\ilcomuneinforma.it\\UnCSS\\node_modules\\canvas\\build\\Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\canvas\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Utente\\Dropbox\\Siti internet\\Altri siti\\ilcomuneinforma.it\\UnCSS\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\canvas
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_path=C:\Users\Utente\Dropbox\Siti internet\Altri siti\ilcomuneinforma.it\UnCSS\node_modules\canvas\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm WARN myuncss@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Utente\AppData\Roaming\npm-cache\_logs\2019-01-24T17_51_03_379Z-debug.log
```

I'd like to avoid a Python compile if I can, how do I tell npm: "simply install pre-built canvas"?

**Comment by zbjornson** [comment]
> npm install --save-dev canvas-prebuild

That should be `canvas-prebuilt` with a T.

> npm install --save-dev canvas

This one is failing because Windows prebuilds are broken for 2.3.0 and 2.3.1. I think canvas@2.2.0 will work. (https://github.com/Automattic/node-canvas/issues/1351)
