### ISSUE TITLE
A question ... import Canvas from "canvas-prebuilt" ... Canvas is null...

### ISSUE THREAD

**Issue by arifullahjan** [node-gfx/node-canvas-prebuilt#48]
``` typescript
import Canvas from 'canvas-prebuilt';


const qrFor = (textToEncode: String,tempFile:any):Promise<String> => {

  const canvas =  new Canvas(500, 500);
  return new Promise((resolve,reject)=>{
    // const ctx = canvas.getContext('2d');
    QrCode.toFile(tempFile,textToEncode,
      {
        color: {
          dark: '#00F',  // Blue dots
          light: '#0000' // Transparent background
        }
      },
      (err) => {
        if(err){
          reject();

        }
        else{
          // const out = fs.createWriteStream(tempFile);
          // const stream = canvas.createJPEGStream();
          // stream.pipe(out);
          // out.on('finish', () =>  {
          //   console.log("saved temp qr");
          //   resolve();
          // });
          resolve();
        }




      });


  });
```

Here is my  code and I am getting  this error ... Please help

```
canvas_prebuilt_1.default is not a function
    at qrFor (/user_code/lib/qr/generate_qr.js:15:45)
    at Object.genrateProductQr [as default] (/user_code/lib/qr/generate_qr.js:56:12)
    at exports.helloWorld.functions.https.onRequest (/user_code/lib/index.js:31:33)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/providers/https.js:37:41)
    at /var/tmp/worker/worker.js:684:7
    at /var/tmp/worker/worker.js:668:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by arifullahjan** [comment]
Following cloudfunctions samples image-maker https://github.com/firebase/functions-samples/blob/master/image-maker/functions/index.js

**Comment by arifullahjan** [comment]
I found out that the import actually returns null...

**Comment by arifullahjan** [comment]
And that's because the typscript is  changing 
`import Canvas from 'canvas-prebuilt'`
to 
`cost convas-prebuilt-1   = require(...);`

**Comment by zbjornson** [comment]
Try `import {Canvas} from "canvas-prebuilt"`. There is no default export. (See [this](https://github.com/Automattic/node-canvas/blob/master/index.js#L51).)

**Comment by arifdigibaad** [comment]
Yeah.... You are right. Sorry I forgot to close this issue.
