### ISSUE TITLE
Works on Windows, doesn't work on Linux

### ISSUE THREAD

**Issue by folmert** [node-gfx/node-canvas-prebuilt#49]
Test on a component which is using vue-chartjs (which is based on canvas) runs fine on Windows, but fails to run on Linux machine:

> Step 8/10 : RUN yarn test:unit
>  ---> Running in 7ecc871d2a00
> yarn run v1.3.2
> $ vue-cli-service test:unit
> Using API URL:  http://localhost
>   console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
>     Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
>         at module.exports (/app/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
>         at HTMLCanvasElementImpl.getContext (/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
>         at HTMLCanvasElement.getContext (/app/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
>         at VueComponent.renderChart (/app/node_modules/vue-chartjs/dist/webpack:/src/BaseCharts.js:68:29)
>         at VueComponent.mounted (/app/src/components/ui/ChartLine.vue:96:1)
>         at callHook (/app/node_modules/vue/dist/vue.runtime.common.js:2919:21)
>         at mountComponent (/app/node_modules/vue/dist/vue.runtime.common.js:2800:5)
>         at VueComponent.Object.<anonymous>.Vue.$mount (/app/node_modules/vue/dist/vue.runtime.common.js:7997:10)
>         at mount (/app/node_modules/@vue/test-utils/dist/vue-test-utils.js:4659:8)
>         at shallow (/app/node_modules/@vue/test-utils/dist/vue-test-utils.js:4691:10) undefined

Dependencies from package.json:
```
"dependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-rc.5",
    "@vue/cli-plugin-e2e-cypress": "^3.0.0-rc.5",
    "@vue/cli-plugin-eslint": "^3.0.0-rc.5",
    "@vue/cli-plugin-unit-jest": "^3.0.0-rc.5",
    "@vue/cli-service": "^3.0.0-rc.5",
    "@vue/eslint-config-prettier": "^3.0.0-rc.5",
    "@vue/server-test-utils": "^1.0.0-beta.20",
    "@vue/test-utils": "1.0.0-beta.12",
    "axios": "^0.18.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.2.0",
    "bootstrap": "4.1.0",
    "bootstrap-vue": "^2.0.0-rc.11",
    "canvas-prebuilt": "1.6.5-prerelease.1",
    "chart.js": "^2.7.2",
    "element-ui": "^2.4.3",
    "eslint-plugin-jest": "^21.17.0",
    "eslint-plugin-vue": "^4.7.0",
    "flat": "^4.0.0",
    "jest-canvas-mock": "^1.1.0",
    "lint-staged": "^7.2.0",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "moment-locales-webpack-plugin": "^1.0.7",
    "node-sass": "^4.9.0",
    "query-string": "^5.1.1",
    "sass-loader": "^7.0.3",
    "sinon": "^6.1.0",
    "svg-sprite-loader": "^3.9.0",
    "svgo": "^1.0.5",
    "svgo-loader": "^2.1.0",
    "vee-validate": "^2.0.9",
    "vue": "^2.5.16",
    "vue-chartjs": "^3.3.2",
    "vue-clipboard2": "^0.1.1",
    "vue-date": "^1.1.10",
    "vue-peity": "^0.5.0",
    "vue-router": "^3.0.1",
    "vue-toasted": "^1.1.24",
    "vue-upload-component": "^2.8.9",
    "vuebar": "^0.0.18",
    "vuex": "^3.0.1",
    "vuex-router-sync": "^5.0.0"
  },
```

**Comment by BrummbQ** [comment]
Same issue here with node 10.5.0 on arch linux

**Comment by antonovicha** [comment]
We have same / similar problem. Works in windows 10 and docker "ubuntu/trusty64" image. But fails with same error on fedora.

**Comment by chearon** [comment]
The stack trace in the issue comment is jsdom, and I don't know anything about that, sorry. What happens when you `require("canvas-prebuilt")`?

**Comment by antonovicha** [comment]
In our case after adding `require("canvas-prebuilt")` application crashes on start, not on html via jsdom manipulation.

**Comment by antonovicha** [comment]
After installing libpng12 our problem go away. Keep in mind that you need to install 64 bit version for 64 bit OS: `sudo yum install libpng12.x86_64`. Running `yum install libpng12` will isntall only 32 bit one and problem will stay for 64 bit OS.

@chearon may be it should be mentioned in documentation? Or may be canvas-prebuilt will start to bundle libpng12 as it does with other libraries? Here is lib load sequence on fedora:
```
strace -e trace=open node bin/www

open("PATH_TO_APP/node_modules/canvas-prebuilt/canvas/build/Release/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 10
open("/lib64/tls/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/tls/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/tls/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/tls/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("PATH_TO_APP/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js", O_RDONLY|O_CLOEXEC) = 10
```

**Comment by chearon** [comment]
Everyone here is using `1.6.5-prerelease.1`, and that version **doesn't** ship `libpng12` because that version of the build considers it a system dependency. The 2.x series doesn't have that issue (it ships `libpng16`).

Is using `canvas-prebuilt@next` (the 2.x series) a viable solution for everyone? It uses the newer build that works on a much broader range of distributions (despite the `alpha` in its name, Canvas 2 has been in development for a few years and there haven't been many big issues with it).

I would just add some `1.6.x` versions that use the newer build, but that would mean a semver-patch upgrade changes the library/binary structure significantly...

**Comment by antonovicha** [comment]
I will try to switch. However our dev effort focus switched for now. So my results could be delayed.

**Comment by antonovicha** [comment]
After switching version to 2.0.0-alpha.13 and removing libpng12 from system `using require('canvas-prebuilt');` dose not crash anymore. However app crashes with:
```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (PATH_TO_APP/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (PATH_TO_APP/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (PATH_TO_APP/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
    at s (about:blank:21:1145)
```
It looks like support of canvas-prebuilt 2.0 wont be added to jsdom while canvas-prebuilt version is still alpha. See https://github.com/Automattic/node-canvas/issues/978#issuecomment-327568435 and https://github.com/jsdom/jsdom/pull/1964#issuecomment-326359348.
