### ISSUE TITLE
Procedure not found

### ISSUE THREAD

**Issue by arifullahjan** [node-gfx/node-canvas-prebuilt#55]
node --version
v8.12.0

windows x64

I get the following error. Using it in firebase functions. The same code runs on osx.

+  functions: Finished running predeploy script.
i  functions: ensuring necessary APIs are enabled...
+  functions: all necessary APIs are enabled
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: The specified procedure could not be found.
\\?\C:\Users\Arif\Documents\GitHub\digibaad-functions\functions\node_modules\canvas-prebuilt\canvas\build\Release\canvas.node
    at Object.Module._extensions..node (module.js:682:18)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Arif\Documents\GitHub\digibaad-functions\functions\node_modules\canvas-prebuilt\canvas\lib\bindings.js:3:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! digibaad-cloud-functions@0.11.0 deploy: `firebase deploy --only functions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the digibaad-cloud-functions@0.11.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arif\AppData\Roaming\npm-cache\_logs\2018-10-06T11_26_20_352Z-debug.log
PS C:\Users\Arif\Documents\GitHub\digibaad-functions\functions>

**Comment by wintercounter** [comment]
It tries to load from the wrong place. It's in an `obj` folder inside it's `Release` folder where it tries to look.

**Comment by wintercounter** [comment]
Same here.

**Comment by arifullahjan** [comment]
@reaby How did you downgrade it to alpha.13. The previous version works but I wasn't able to downgrade it. Npm automatically installed apha.14. Can you please tell me why?

**Comment by reaby** [comment]
@arifullahjan 

change your packages.json to ``` 
    "canvas-prebuilt": "2.0.0-alpha.13",
```
and run npm install again.

but, i think you really should migrate to new canvas, which has prebuilt migrated already!
`npm install canvas@2.0.1` it works nicely without jsdom already.

and will work with jsdom after https://github.com/jsdom/jsdom/pull/1964 gets merged!
(hopefully later today, or during next week)
