### ISSUE TITLE
Automatically trigger and publish prebuilds

### ISSUE THREAD

**Issue by zbjornson** [node-gfx/node-canvas-prebuilt#57]
A large number of new issues come from prebuilds not yet existing for recent canvas releases. Ideally we trigger prebuilds with a GitHub hook.

**Comment by chearon** [comment]
Both [travis](https://docs.travis-ci.com/user/triggering-builds/#customizing-the-build-configuration) and [appveyor](https://www.appveyor.com/docs/deployment/webhook/) let you specify env variables so it's possible when a new tag is pushed to node-canvas. I think I'd still have to make something to draft a new release here, since right now that's manual. @LinusU would still probably want to make sure the builds worked before `npm publish` since every now and then something goes wrong.

**Comment by asturur** [comment]
Also somehow pre-builds lack svg support.
I removed my node-modules folder, pulled down 2.0.1, and run npm install.
I can see from console i get the prebuilt package, but then when i run the local test server:
![image](https://user-images.githubusercontent.com/1194048/47268936-503f5900-d557-11e8-8210-55d523c54180.png)

and in my console:
```
👉  http://localhost:4000/
Error: node-canvas was built without SVG support
    at setSource (/Users/abogazzi/fabric/node-canvas/lib/image.js:102:14)
    at Image.set (/Users/abogazzi/fabric/node-canvas/lib/image.js:65:9)
    at Object.tests.drawImage(img) svg (/Users/abogazzi/fabric/node-canvas/test/public/tests.js:1893:11)
    at renderTest (/Users/abogazzi/fabric/node-canvas/test/server.js:21:16)
    at /Users/abogazzi/fabric/node-canvas/test/server.js:42:3
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/index.js:281:22
Error: node-canvas was built without SVG support
    at setSource (/Users/abogazzi/fabric/node-canvas/lib/image.js:102:14)
    at Image.set (/Users/abogazzi/fabric/node-canvas/lib/image.js:65:9)
    at Object.tests.drawImage(img) svg with scaling from drawImage (/Users/abogazzi/fabric/node-canvas/test/public/tests.js:1903:11)
    at renderTest (/Users/abogazzi/fabric/node-canvas/test/server.js:21:16)
    at /Users/abogazzi/fabric/node-canvas/test/server.js:42:3
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/index.js:281:22
Error: node-canvas was built without SVG support
    at setSource (/Users/abogazzi/fabric/node-canvas/lib/image.js:102:14)
    at Image.set (/Users/abogazzi/fabric/node-canvas/lib/image.js:65:9)
    at Object.tests.drawImage(img) svg with scaling from ctx (/Users/abogazzi/fabric/node-canvas/test/public/tests.js:1914:11)
    at renderTest (/Users/abogazzi/fabric/node-canvas/test/server.js:21:16)
    at /Users/abogazzi/fabric/node-canvas/test/server.js:42:3
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/index.js:281:22
```
