### ISSUE TITLE
libsrvg missing from prebuilts

### ISSUE THREAD

**Issue by asturur** [node-gfx/node-canvas-prebuilt#59]
replace comment on #57 

Also somehow pre-builds lack svg support. 
I removed my node-modules folder, pulled down 2.0.1, and run npm install.
I can see from console i get the prebuilt package, but then when i run the local test server:
![image](https://user-images.githubusercontent.com/1194048/47268936-503f5900-d557-11e8-8210-55d523c54180.png)

and in my console:
```
👉  http://localhost:4000/
Error: node-canvas was built without SVG support
    at setSource (/Users/abogazzi/fabric/node-canvas/lib/image.js:102:14)
    at Image.set (/Users/abogazzi/fabric/node-canvas/lib/image.js:65:9)
    at Object.tests.drawImage(img) svg (/Users/abogazzi/fabric/node-canvas/test/public/tests.js:1893:11)
    at renderTest (/Users/abogazzi/fabric/node-canvas/test/server.js:21:16)
    at /Users/abogazzi/fabric/node-canvas/test/server.js:42:3
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/index.js:281:22
Error: node-canvas was built without SVG support
    at setSource (/Users/abogazzi/fabric/node-canvas/lib/image.js:102:14)
    at Image.set (/Users/abogazzi/fabric/node-canvas/lib/image.js:65:9)
    at Object.tests.drawImage(img) svg with scaling from drawImage (/Users/abogazzi/fabric/node-canvas/test/public/tests.js:1903:11)
    at renderTest (/Users/abogazzi/fabric/node-canvas/test/server.js:21:16)
    at /Users/abogazzi/fabric/node-canvas/test/server.js:42:3
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/index.js:281:22
Error: node-canvas was built without SVG support
    at setSource (/Users/abogazzi/fabric/node-canvas/lib/image.js:102:14)
    at Image.set (/Users/abogazzi/fabric/node-canvas/lib/image.js:65:9)
    at Object.tests.drawImage(img) svg with scaling from ctx (/Users/abogazzi/fabric/node-canvas/test/public/tests.js:1914:11)
    at renderTest (/Users/abogazzi/fabric/node-canvas/test/server.js:21:16)
    at /Users/abogazzi/fabric/node-canvas/test/server.js:42:3
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/layer.js:95:5)
    at /Users/abogazzi/fabric/node-canvas/node_modules/express/lib/router/index.js:281:22
```

This happen on macos 10.13

**Comment by zbjornson** [comment]
Guess this is the same as https://github.com/Automattic/node-canvas/issues/1248, but will leave both open for visibility.

**Comment by LinusU** [comment]
Maybe related to #42 as well?

**Comment by chearon** [comment]
Done! (As of `canvas@2.1.0`)
