### ISSUE TITLE
Can't Install on macOS

### ISSUE THREAD

**Issue by eiskalteschatten** [node-gfx/node-canvas-prebuilt#83]
When running `npm install --save-dev canvas-prebuilt`, I get the following stack trace:

```
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v72-darwin-unknown-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/alexseifert/Sites/compositeur/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:208:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/alexseifert/Sites/compositeur/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:203:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:203:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/alexseifert/Sites/compositeur/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/alexseifert/Sites/compositeur/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v2.0.0-alpha.14/canvas-prebuilt-v2.0.0-alpha.14-node-v72-darwin-unknown-x64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@2.0.0-alpha.14 install: `node-pre-gyp install`
npm ERR! Exit status 1
```

I haven't tested it on any other OS than macOS 10.14.6 with Node 12.7.0.

I also get the following when I try to install the latest stable version (1.6.11) with `npm install --save-dev canvas-prebuilt@1.6.11`:

```
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/alexseifert/Sites/compositeur/node_modules/canvas-prebuilt/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:208:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/alexseifert/Sites/compositeur/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:203:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:575:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:203:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
node-pre-gyp ERR! System Darwin 18.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/alexseifert/Sites/compositeur/node_modules/canvas-prebuilt/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /Users/alexseifert/Sites/compositeur/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v12.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v72-darwin-x64.tar.gz
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm ERR! Exit status 1
```

**Comment by eiskalteschatten** [comment]
Any updates here?

**Comment by eiskalteschatten** [comment]
Never mind. Just saw node-canvas-prebuilt is deprecated.
